<?php
/**
 * Sandbox module that creates nodes/menu items/taxonomy items from a simple yaml file
 * for testing and initial content if you develop in a clean-build environment.
 *
 * PHP Version 5.3
 */
use Drupal\Fixtures\Providers\FixtureProviderChainInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * implementation of hook_menu()
 */
function fixtures_menu() {
  $items = array();
  $items['debug_menus'] = array(
    'title' => 'debugging fixtures',
    'description' => 'bogus function for debugging fixtures',
    'page callback' => 'fixtures_create_menus',
    'access arguments' => array('access content'),
    'file' => 'fixtures.menu.inc'
  );
  $items['debug_nodes'] = array(
    'title' => 'debugging fixtures',
    'description' => 'bogus function for debugging fixtures',
    'page callback' => 'fixtures_create_nodes',
    'access arguments' => array('access content'),
    'file' => 'fixtures.node.inc'
  );
  return $items;
}